In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [11]:
array_1d = np.array([1, 2, 3, 4, 5])

In [12]:
array_1d

array([1, 2, 3, 4, 5])

In [13]:
print(array_1d)


[1 2 3 4 5]


In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]]).reshape(3, 2)

In [25]:
array_2d.dtype

dtype('int64')

In [26]:
array_2d.shape

(2, 3)

In [28]:
array_2d.size

6

In [29]:
array_1d = np.arange(0,12)

In [30]:
array_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
array_1d.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [42]:
array_1d.reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [37]:
array_1d.reshape(1 ,12 )

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [43]:
array_1d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])